name: Mirror to DRSCrafter/karsu-backend

on:
  push:
    branches: ['**']
    tags: ['**']
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history, no creds)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Remove default auth header
        run: git config --unset-all http.https://github.com/.extraheader || true

      - name: Configure Git author
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add mirror remote (destination)
        run: |
          git remote add mirror "https://x-access-token:${{ secrets.MIRROR_TOKEN }}@github.com/DRSCrafter/karsu-backend.git"

      - name: Create local branches from origin/*
        run: |
          git fetch --all --tags
          for b in $(git for-each-ref --format='%(refname:strip=3)' refs/remotes/origin); do
            git branch -f "$b" "origin/$b"
          done

      # Optional LFS
      # - name: Install & fetch LFS
      #   run: |
      #     git lfs install
      #     git lfs fetch --all
      # - name: Push LFS objects
      #   run: git lfs push --all mirror

      - name: Push branches and tags (prune deletions)
        run: |
          git push --prune mirror 'refs/heads/*:refs/heads/*' 'refs/tags/*:refs/tags/*'
